In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv("cleaned_dataset.csv")
df.head()

,Brand,Current Price,Original Price,Discount Percentage,Rating,Number OF Ratings,Model Name,Dial Shape,Strap Color,Strap Material,Touchscreen,Battery Life (Days),Bluetooth,Display Size,Weight
0,noise,82990.0,89900.0,7.686318,4.0,65.0,Wrb-sw-colorfitpro4alpha-std-rgld_pnk,Circle,Black,Silicon,1,8.0,1,1.5,35 - 50 g
1,fire-boltt,3799.0,16999.0,77.651627,4.3,20788.0,BSW046,Circle,Black,Silicon,1,3.5,1,1.8,50 - 75 g
2,boat,1999.0,7990.0,74.981227,3.8,21724.0,Wave Call,Circle,Black,Silicon,1,8.0,1,1.7,35 - 50 g
3,fire-boltt,1799.0,19999.0,91.004550,4.3,13244.0,BSW053,Circle,Black,Silicon,1,3.5,1,1.8,75g +
4,noise,1599.0,4999.0,68.013603,4.1,13901.0,Wrb-sw-colorfitpulsegobuzz-std-blk_blk,Circle,Black,Other,1,8.0,1,1.7,35 - 50 g

In [3]:
df.describe(include=object)

             Brand Model Name Dial Shape Strap Color Strap Material     Weight
count          440        440        440         440            440        440
unique          18        390          6          30             15          5
top     fire-boltt    Unknown     Circle       Black        Silicon  20 - 35 g
freq            56         33        244         246            307        264