# Smartwatch Rating Prediction: Model Training

### Objective

- The objective of this notebook is to train multiple regression algorithms on the processed smartwatch dataset and compare their performance.

### Algorithms

- Linear Regression
- Decision Tree
- Ridge
- Lasso
- KNN
- Random Forest
- Gradient Boosting
- XGBoost

In [346]:
import pandas as pd
import numpy as np
import joblib

from pathlib import Path
from xgboost import XGBRegressor
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.tree import DecisionTreeRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor

EXPERIMENTS_DIR = Path.cwd().parent / "experiments" / "baseline" / "models"

### Load Processed Dataset

In [347]:
SPLITS_DIR = Path.cwd().parent / "Dataset" / "split"
COMPARISON_DIR = Path.cwd().parent / "experiments" / "baseline" / "comparison"

X_train = pd.read_csv(SPLITS_DIR / "X_train.csv")
X_test = pd.read_csv(SPLITS_DIR / "X_test.csv")
y_train = pd.read_csv(SPLITS_DIR / "y_train.csv").squeeze()
y_test = pd.read_csv(SPLITS_DIR / "y_test.csv").squeeze()

#Scaled Data
X_train_scaled = pd.read_csv(SPLITS_DIR / "X_train_scaled.csv")
X_test_scaled = pd.read_csv(SPLITS_DIR / "X_test_scaled.csv")

In [348]:
print(X_train.shape)
print(X_test.shape)

print(y_train.shape)
print(y_test.shape)

(277, 22)
(70, 22)
(277,)
(70,)

# LinearRegression

In [349]:
model=LinearRegression()

In [350]:
model.fit(X_train, y_train)

LinearRegression()

In [351]:
model.coef_

array([-1.82813347e-05,  2.28747666e-05, -6.00577761e-03,  5.90282140e-02,
        1.56655619e-03,  3.02411111e-02, -4.93238200e-02, -1.95406623e-01,
       -2.35978216e-01, -2.01748504e-02,  3.40841573e-02, -1.81428733e-01,
       -3.45342493e-01,  8.19936807e-02, -1.32288342e-01,  6.12416051e-02,
        1.41486012e-01, -1.51594177e-01, -1.04965811e-01, -8.96175905e-03,
       -9.04735816e-02, -2.51815353e-01])

In [352]:
model.intercept_

np.float64(4.405079439586312)

In [353]:
y_pred = model.predict(X_test)
y_pred

array([3.37458201, 4.0893859 , 3.80354215, 4.06806777, 3.96864231,
       3.90820382, 4.16866253, 4.0703045 , 3.91978776, 4.33088942,
       4.13212114, 4.1600301 , 4.39941521, 4.1964478 , 4.07887716,
       4.4432578 , 4.02511673, 3.85788824, 3.90785591, 4.0965903 ,
       4.089997  , 3.68750621, 3.94680373, 4.01404558, 3.77818485,
       3.95052686, 4.02957289, 4.11829999, 4.07508417, 3.70711302,
       4.11918247, 4.11514454, 4.18506791, 3.97459452, 4.1097251 ,
       3.78860496, 4.39627303, 4.05045126, 3.91123776, 4.01652441,
       4.17674103, 3.96202927, 4.14345902, 4.09255095, 4.13299745,
       4.04337898, 3.66280542, 4.07397973, 4.11633108, 3.95702778,
       4.13595653, 4.20013663, 4.57935912, 4.03729353, 4.00313984,
       4.58607058, 4.0678624 , 3.746637  , 4.31966419, 4.27427711,
       4.27355903, 3.86978368, 3.53441341, 3.86118194, 3.95258424,
       3.93796901, 4.46505348, 4.26556927, 4.35778243, 3.69592608])

In [354]:
coef_df=pd.DataFrame({"feature":X_train.columns, "Coefficient": model.coef_})
coef_df= coef_df.sort_values(by='Coefficient', ascending=False)
coef_df.head(10)

                     feature  Coefficient
16         Dial Shape_Square     0.141486
13        Dial Shape_Missing     0.081994
15      Dial Shape_Rectangle     0.061242
3          Number OF Ratings     0.059028
10  reviews_placeholder_flag     0.034084
5               Display Size     0.030241
4        Battery Life (Days)     0.001567
1             Original Price     0.000023
0              Current Price    -0.000018
2        Discount Percentage    -0.006006

In [355]:
y_test

0     2.3
1     4.4
2     2.9
3     4.7
4     3.9
     ...
65    3.9
66    4.1
67    4.3
68    4.4
69    3.1
Name: Rating, Length: 70, dtype: float64

In [356]:
comparison_LR=pd.DataFrame({"Actual Ratings":y_test, "Predicted Ratings": y_pred})

In [357]:
comparison_LR.head(10)

   Actual Ratings  Predicted Ratings
0             2.3           3.374582
1             4.4           4.089386
2             2.9           3.803542
3             4.7           4.068068
4             3.9           3.968642
5             4.0           3.908204
6             4.1           4.168663
7             4.5           4.070304
8             3.6           3.919788
9             4.3           4.330889

In [358]:
joblib.dump(model,  EXPERIMENTS_DIR / "Linear_Regression.joblib")

print('Linear Regression Model Saved Successfully !!!')

Linear Regression Model Saved Successfully !!!

In [359]:
comparison_LR.to_csv(COMPARISON_DIR / "Comparison_Linear_Regression.csv", index=False)

# DecisionTreeRegressor

In [360]:
DT_model=DecisionTreeRegressor(random_state=42)

In [361]:
DT_model.fit(X_train,y_train)

DecisionTreeRegressor(random_state=42)

In [362]:
feature_importance=pd.DataFrame({"Feature":X_train.columns,
                                 "Feature_Importance":DT_model.feature_importances_
                                }).sort_values(by='Feature_Importance', ascending=False)
feature_importance.head(10)

                   Feature  Feature_Importance
3        Number OF Ratings            0.304304
0            Current Price            0.199915
9           Weight_ordinal            0.124723
5             Display Size            0.091181
17  Strap Material_Missing            0.085664
2      Discount Percentage            0.070954
1           Original Price            0.050473
8         Strap_Color_freq            0.014469
7               Brand_freq            0.013312
19   Strap Material_Rubber            0.011125

In [363]:
y_pred_DT=DT_model.predict(X_test)
y_pred_DT

array([5. , 4.1, 3.1, 4. , 3.9, 4. , 3.8, 4.5, 3.3, 4.3, 4. , 3.9, 4.3,
       4.1, 4.3, 4.2, 3.8, 4. , 3.8, 4.2, 3.8, 2.4, 4.1, 4. , 4.3, 4.1,
       4.1, 4.1, 4.2, 5. , 4. , 4.1, 4.2, 3.6, 3.7, 4.2, 4.2, 4.1, 3.6,
       3.7, 3.9, 4.1, 4.1, 4. , 4.2, 4.2, 3.3, 4. , 3.8, 4.2, 3.7, 4.3,
       4.7, 3.7, 4.2, 4.7, 3.5, 5. , 4. , 4.2, 4.7, 4.1, 2.4, 4.3, 4.7,
       3.9, 4.3, 2.6, 3.8, 3.5])

In [364]:
comparison_DT= pd.DataFrame({
    "Actual Rating": y_test,
    "Predicted Rating": y_pred_DT
})

comparison_DT.head()

   Actual Rating  Predicted Rating
0            2.3               5.0
1            4.4               4.1
2            2.9               3.1
3            4.7               4.0
4            3.9               3.9

In [365]:
comparison_DT.to_csv(COMPARISON_DIR / "Comparison_Decision_Tree_Predictions.csv", index=False)

In [366]:
joblib.dump(DT_model,  EXPERIMENTS_DIR /"Decision_Tree_Model.joblib")
print("Decision Tree Model Saved Successfully !!!")

Decision Tree Model Saved Successfully !!!

# Ridge

In [367]:
ridge_model=Ridge(alpha=1.0)

In [368]:
ridge_model.fit(X_train_scaled,y_train)

Ridge()

In [369]:
X_test

,Current Price,Original Price,Discount Percentage,Number OF Ratings,Battery Life (Days),Display Size,Weight_missing,Brand_freq,Strap_Color_freq,Weight_ordinal,...,Bluetooth,Dial Shape_Missing,Dial Shape_Other,Dial Shape_Rectangle,Dial Shape_Square,Strap Material_Missing,Strap Material_Other,Strap Material_Rubber,Strap Material_Silicon,Strap Material_Stainless Steel
0,3099.0,7999.0,61.257657,1.386294,22.000000,0.1,1,0.090253,0.241877,1.0,...,1,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,3999.0,6999.0,42.863266,9.431081,22.000000,1.4,1,0.104693,0.303249,1.0,...,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,3449.0,4199.0,17.861396,2.890372,3.500000,2.4,1,0.090253,0.303249,1.0,...,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1499.0,6999.0,78.582655,6.904751,22.000000,1.9,0,0.072202,0.090253,1.0,...,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
4,2199.0,4999.0,56.011202,5.609472,22.000000,1.5,0,0.090253,0.241877,1.0,...,1,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,3599.0,10999.0,67.278844,7.385231,8.000000,1.5,0,0.090253,0.288809,3.0,...,1,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
66,20590.0,21499.0,4.228104,8.406485,3.500000,1.3,0,0.018051,0.303249,1.0,...,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
67,7499.0,16999.0,55.885640,9.351927,8.000000,1.4,0,0.122744,0.090253,0.0,...,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
68,24990.0,36490.0,31.515484,3.784190,22.000000,1.2,0,0.086643,0.241877,1.0,...,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
69,2949.0,4199.0,29.768993,2.397895,14.077392,2.7,1,0.090253,0.303249,1.0,...,1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [370]:
y_pred_ridge=ridge_model.predict(X_test_scaled)

In [371]:
coef_Ridge = pd.DataFrame({
    "Feature": X_train.columns,
    "Coefficient": ridge_model.coef_}).sort_values(by='Coefficient', ascending=False)

coef_Ridge.head()

                 Feature  Coefficient
1         Original Price     0.304872
3      Number OF Ratings     0.158695
16     Dial Shape_Square     0.054747
13    Dial Shape_Missing     0.029986
15  Dial Shape_Rectangle     0.019108

### Comparing coefficient: Linear Regression vs Ridge

In [372]:
comparison_coef=pd.DataFrame({"Features":X_train.columns,
                              "Linear Coefficient":model.coef_,
                              "Ridge Coefficient": ridge_model.coef_})
comparison_coef["Difference"]=(comparison_coef['Linear Coefficient']-comparison_coef['Ridge Coefficient'])
comparison_coef.sort_values(by='Difference', ascending =False)
comparison_coef

,Features,Linear Coefficient,Ridge Coefficient,Difference
0,Current Price,-0.000018,-0.200976,0.200958
1,Original Price,0.000023,0.304872,-0.304849
2,Discount Percentage,-0.006006,-0.120150,0.114144
3,Number OF Ratings,0.059028,0.158695,-0.099667
4,Battery Life (Days),0.001567,0.010078,-0.008512
5,Display Size,0.030241,0.016682,0.013559
6,Weight_missing,-0.049324,-0.025485,-0.023839
7,Brand_freq,-0.195407,-0.006359,-0.189048
8,Strap_Color_freq,-0.235978,-0.016324,-0.219654
9,Weight_ordinal,-0.020175,-0.024672,0.004497
10,reviews_placeholder_flag,0.034084,0.010520,0.023564
11,Touchscreen,-0.181429,-0.030287,-0.151142
12,Bluetooth,-0.345342,-0.020755,-0.324588
13,Dial Shape_Missing,0.081994,0.029986,0.052008
14,Dial Shape_Other,-0.132288,-0.008538,-0.123750
15,Dial Shape_Rectangle,0.061242,0.019108,0.042134
16,Dial Shape_Square,0.141486,0.054747,0.086739
17,Strap Material_Missing,-0.151594,-0.054342,-0.097252
18,Strap Material_Other,-0.104966,-0.037117,-0.067849
19,Strap Material_Rubber,-0.008962,-0.001948,-0.007014
20,Strap Material_Silicon,-0.090474,-0.044559,-0.045915
21,Strap Material_Stainless Steel,-0.251815,-0.044029,-0.207786

In [373]:
comparison_ridge= pd.DataFrame({
    "Actual Rating": y_test,
    "Predicted Rating": y_pred_ridge
})

comparison_ridge.head()

   Actual Rating  Predicted Rating
0            2.3          3.374836
1            4.4          4.093016
2            2.9          3.810564
3            4.7          4.078635
4            3.9          3.976524

In [374]:
comparison_ridge.to_csv(COMPARISON_DIR / "Comparison_Ridge.csv", index=False)

In [375]:
joblib.dump(ridge_model, EXPERIMENTS_DIR /"Ridge_Model.joblib")
print("Ridge Model Saved Successfully !!!")

Ridge Model Saved Successfully !!!

# Lasso

In [376]:
lasso_model=Lasso(alpha=1.0)

In [377]:
lasso_model.fit(X_train_scaled,y_train)

Lasso()

In [378]:
lasso_model.coef_

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.])

In [379]:
lasso_model.intercept_

np.float64(4.072202166064982)

In [380]:
y_pred_Lasso = lasso_model.predict(X_test_scaled)

In [381]:
coef_lasso=pd.DataFrame({"Feature":X_train.columns, "Coefficient":lasso_model.coef_}).sort_values(by="Coefficient", ascending=False)

### Comparing Actual Values and Predicted Values

In [382]:
comparison_lasso=pd.DataFrame({"Actual Values":y_test, "Predicted Values":y_pred_Lasso})

In [383]:
comparison_lasso.to_csv(COMPARISON_DIR / "Comparison_Lasso.csv", index=False)

In [384]:
joblib.dump(lasso_model,  EXPERIMENTS_DIR /"Lasso_Model.joblib")
print("Lasso Model saved successfully !!!")

Lasso Model saved successfully !!!

# KNeighboursRegressor

In [385]:
# Keeping Neighbours=5 fro baseline
knn_model=KNeighborsRegressor(n_neighbors=5)

In [386]:
knn_model.fit(X_train_scaled, y_train)

KNeighborsRegressor()

In [387]:
y_pred_knn=knn_model.predict(X_test_scaled)

In [388]:
y_pred_knn

array([3.94, 4.2 , 3.98, 4.08, 4.18, 4.18, 4.34, 4.26, 4.1 , 4.36, 4.04,
       4.1 , 4.4 , 4.08, 4.3 , 4.06, 4.1 , 3.66, 3.82, 4.24, 4.46, 3.62,
       3.92, 3.78, 3.84, 4.1 , 4.  , 4.08, 4.1 , 4.1 , 4.06, 4.16, 4.08,
       3.96, 3.88, 3.44, 3.96, 4.1 , 4.06, 3.92, 4.1 , 4.02, 4.08, 4.04,
       4.14, 4.18, 3.44, 4.2 , 4.06, 3.84, 3.92, 4.18, 4.7 , 3.78, 4.14,
       4.4 , 4.  , 3.96, 4.12, 4.06, 4.14, 4.18, 3.04, 3.92, 3.84, 3.78,
       4.18, 4.16, 4.46, 3.8 ])

In [389]:
comparison_knn=pd.DataFrame({"Actual Values":y_test, "Predicted Values":y_pred_knn})

In [390]:
comparison_knn.to_csv(COMPARISON_DIR / "Comparison_KNN.csv", index=False)

In [391]:
joblib.dump(knn_model, EXPERIMENTS_DIR /"KNN_Model.joblib")
print("KNN Model Saved Successfully !!!")

KNN Model Saved Successfully !!!

# RandomForestRegressor

In [392]:
# 100 trees(Baseline)

rfr_model=RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

In [393]:
rfr_model.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [394]:
y_pred_rfr=rfr_model.predict(X_test)

In [395]:
y_pred_rfr.shape

(70,)

### Feature Importance

In [396]:
feature_importance_rfr=pd.DataFrame({"Features":X_train.columns, "Feature Importance":rfr_model.feature_importances_}).sort_values(by="Feature Importance", ascending=False)

In [397]:
feature_importance_rfr.head(10)

               Features  Feature Importance
3     Number OF Ratings            0.388569
0         Current Price            0.167852
1        Original Price            0.101294
2   Discount Percentage            0.084294
9        Weight_ordinal            0.036888
7            Brand_freq            0.036618
5          Display Size            0.036163
4   Battery Life (Days)            0.030090
8      Strap_Color_freq            0.021487
16    Dial Shape_Square            0.015543

In [398]:
comparison_rfr=pd.DataFrame({"Actual Values":y_test, "Predicted Values" : y_pred_rfr})
comparison_rfr

    Actual Values  Predicted Values
0             2.3             4.598
1             4.4             4.186
2             2.9             3.764
3             4.7             4.148
4             3.9             3.856
..            ...               ...
65            3.9             3.953
66            4.1             4.298
67            4.3             3.868
68            4.4             4.111
69            3.1             3.481

[70 rows x 2 columns]

In [399]:
comparison_rfr.to_csv(COMPARISON_DIR / "Comparison_rfr.csv", index=False)

In [400]:
joblib.dump(rfr_model,  EXPERIMENTS_DIR /"RFR_model.joblib")
print("Model Saved Successfully !!!")

Model Saved Successfully !!!

# GradientBoostingRegressor

In [401]:
gbr_model=GradientBoostingRegressor(
    n_estimators=100,
    learning_rate=0.1,
    random_state=42
)

In [402]:
gbr_model.fit(X_train, y_train)

GradientBoostingRegressor(random_state=42)

In [403]:
y_pred_gbr=gbr_model.predict(X_test)
y_pred_gbr.shape

(70,)

In [404]:
feature_importance_gbr=pd.DataFrame({"Features":X_train.columns, "Feature Importance":gbr_model.feature_importances_}).sort_values(by="Feature Importance", ascending=False)
feature_importance_gbr.head(10)

                  Features  Feature Importance
3        Number OF Ratings            0.316043
0            Current Price            0.211942
9           Weight_ordinal            0.114986
1           Original Price            0.103150
2      Discount Percentage            0.084994
7               Brand_freq            0.051242
5             Display Size            0.029041
4      Battery Life (Days)            0.020731
20  Strap Material_Silicon            0.019122
8         Strap_Color_freq            0.013225

In [405]:
comparison_gbr=pd.DataFrame({"Actual values": y_test, "Predicted Values":y_pred_gbr})
comparison_gbr

    Actual values  Predicted Values
0             2.3          4.908566
1             4.4          4.225542
2             2.9          3.681055
3             4.7          4.038975
4             3.9          3.852662
..            ...               ...
65            3.9          3.996408
66            4.1          4.281041
67            4.3          4.110426
68            4.4          4.191688
69            3.1          3.540294

[70 rows x 2 columns]

In [406]:
comparison_gbr.to_csv(COMPARISON_DIR / "Comparison_gbr.csv", index=False)

In [407]:
joblib.dump(gbr_model,  EXPERIMENTS_DIR /"GBR_model.joblib")
print("Model Saved Successfully !!")

Model Saved Successfully !!

# XGBoost

In [408]:
xgb_model=XGBRegressor(
    n_estimators=100,
    learning_rate=0.1,
    random_state=42
)

In [409]:
# Removing any [, ], <, >, =

for col in X_train.columns:
    if "[" in col or "]"in col or "<" in col or  "=" in col:
        print(col)
        X_train.columns=(X_train.columns
            .str.replace("[", "", regex=False)
            .str.replace("]", "", regex=False)
            .str.replace("<", "less than",  regex=False)
            .str.replace(">", "greater than", regex=False)
            .str.replace("=", "equal to", regex=False)
        )
        X_test.columns=(X_test.columns
            .str.replace("[", "", regex=False)
            .str.replace("]", "", regex=False)
            .str.replace("<", "less than", regex=False)
            .str.replace(">", "greater than", regex=False)
            .str.replace("=", "equal to", regex=False)
        )

In [410]:
xgb_model.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.1, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=100,
             n_jobs=None, num_parallel_tree=None, ...)

In [411]:
y_pred_xgb=xgb_model.predict(X_test)

### Feature Importance

In [412]:
feature_importance_xgb=pd.DataFrame({"Features":X_train.columns, "Feature Importance":xgb_model.feature_importances_}).sort_values(by="Feature Importance", ascending=False)
feature_importance.head(10)

                   Feature  Feature_Importance
3        Number OF Ratings            0.304304
0            Current Price            0.199915
9           Weight_ordinal            0.124723
5             Display Size            0.091181
17  Strap Material_Missing            0.085664
2      Discount Percentage            0.070954
1           Original Price            0.050473
8         Strap_Color_freq            0.014469
7               Brand_freq            0.013312
19   Strap Material_Rubber            0.011125

In [413]:
comparison_xgb=pd.DataFrame({"Actual":y_test, "Predicted":y_pred_xgb})
comparison_xgb.to_csv(COMPARISON_DIR / "Comparison_xgb.csv", index=False)

In [414]:
joblib.dump(xgb_model,  EXPERIMENTS_DIR /"XGB_model.joblib")
print("Model Saved successfully !!!")

Model Saved successfully !!!