In [105]:
import pandas as pd
import numpy as np
import joblib
from xgboost import XGBRegressor

from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.tree import DecisionTreeRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor

In [2]:
X_train=pd.read_csv(r"C:\Users\ASUS\OneDrive\Documents\ML Project\Smartwatches project\Dataset\Processed\X_train.csv")
X_test=pd.read_csv(r"C:\Users\ASUS\OneDrive\Documents\ML Project\Smartwatches project\Dataset\Processed\X_test.csv")
y_train=pd.read_csv(r"C:\Users\ASUS\OneDrive\Documents\ML Project\Smartwatches project\Dataset\Processed\y_train.csv").squeeze()
y_test=pd.read_csv(r"C:\Users\ASUS\OneDrive\Documents\ML Project\Smartwatches project\Dataset\Processed\y_test.csv").squeeze()

In [3]:
scaler=StandardScaler()

X_train_scaled=pd.DataFrame(scaler.fit_transform(X_train), columns=X_train.columns)
X_test_scaled=pd.DataFrame(scaler.transform(X_test), columns=X_test.columns)

In [4]:
scaler=StandardScaler()

X_train_scaled=pd.DataFrame(scaler.fit_transform(X_train), columns=X_train.columns)
X_test_scaled=pd.DataFrame(scaler.transform(X_test), columns=X_test.columns)

In [5]:
print(X_train.shape)
print(X_test.shape)

print(y_train.shape)
print(y_test.shape)

(348, 77)
(88, 77)
(348,)
(88,)

# LinearRegression

In [6]:
model=LinearRegression()

In [7]:
model.fit(X_train, y_train)

LinearRegression()

In [8]:
model.coef_

array([ 1.98804019e-06,  2.04180507e-06, -4.29127930e-05,  7.18671013e-07,
        2.65844868e-04,  9.31563310e-02, -1.66930759e+00,  2.64691711e-01,
        1.28246618e-01,  6.95738981e-02,  3.16458431e-01, -1.61285939e-01,
        1.34081051e-01, -1.32766818e-01, -8.36951001e-02,  2.18115950e-01,
       -1.29643737e-01,  2.54608117e-01, -2.05512697e-01, -3.24883134e-01,
        1.23493466e-01,  1.94163296e-01, -2.61400118e-02, -1.67211173e-01,
        9.48133577e-02, -4.70846118e-01, -2.05016000e-01, -6.26434089e-02,
       -1.33171147e-01, -5.94349090e-01,  1.03346822e-01,  2.20952714e-02,
       -3.84842262e-01, -2.54223979e-01, -2.76475940e-01, -3.96463044e-01,
        5.39627989e-01,  1.97790390e-01, -7.34501335e-01, -3.14201696e-01,
       -2.09576945e-01, -2.14574402e-01, -1.26967297e-01,  9.54988488e-02,
       -1.34670787e-01, -1.33171147e-01, -2.80899079e-01, -2.34900786e-01,
        5.63516035e-01, -3.48645082e-01, -2.14735814e-01, -1.96614999e-01,
       -3.05570460e-01, -1.17532696e-01, -3.05685324e-01, -9.59366759e-02,
        6.98192935e-02, -1.55333898e-01, -5.89279677e-01, -3.16153157e-01,
        6.36916322e-02, -3.51907130e-01,  2.84811313e-01,  3.25555754e-01,
        1.92459550e-01,  5.13634401e-01,  2.37476685e-01, -3.63257406e-02,
        3.01744178e-01,  2.97849303e-01,  2.47390882e-01,  9.50857637e-02,
        3.48913182e-01,  1.06422901e-01,  2.83773635e-01, -9.49820359e-03,
        3.22832609e-02])

In [9]:
model.intercept_

np.float64(3.8254329506787967)

In [10]:
y_pred = model.predict(X_test)
y_pred

array([3.65695385, 4.08176733, 4.46235715, 4.14838433, 3.83942346,
       3.88568661, 4.40068723, 4.07022704, 4.10937676, 2.30736659,
       3.82512414, 3.44912955, 4.21664168, 3.63739383, 4.0585761 ,
       2.02235092, 2.66454147, 4.16708168, 3.67671853, 4.25140745,
       4.08839235, 4.04953576, 4.0583695 , 4.07336897, 4.0018337 ,
       4.36437809, 3.71053492, 4.27032245, 4.1052866 , 4.22891557,
       4.09449736, 3.73982641, 4.19418252, 3.90090749, 4.36399604,
       4.00825318, 4.28711612, 3.86498103, 4.1680265 , 4.25447524,
       4.17402671, 4.68853885, 4.08176897, 4.03721236, 4.05985744,
       4.0351899 , 4.17618639, 4.08796572, 4.08268203, 4.38197693,
       3.55825384, 3.73208378, 2.3543874 , 4.42630727, 4.32195695,
       3.9715551 , 4.33538663, 3.90062479, 4.52009773, 4.97668591,
       4.22316527, 3.53898381, 4.02045914, 4.85934392, 3.98984787,
       3.98920371, 3.69080406, 3.94611963, 4.3187445 , 4.21430302,
       4.1808154 , 3.9416539 , 3.61895246, 3.92967112, 4.00729243,
       4.71686848, 3.9812971 , 4.21012955, 4.08926106, 3.24325577,
       4.77132611, 4.46595684, 4.27503662, 4.32493334, 4.27927285,
       4.13571654, 4.07563472, 4.07795518])

In [11]:
coef_df=pd.DataFrame({"feature":X_train.columns, "Coefficient": model.coef_})
coef_df= coef_df.sort_values(by='Coefficient', ascending=False)
coef_df.head(10)

                                       feature  Coefficient
48                      Strap Color_Multicolor     0.563516
36                        Strap Color_Burgundy     0.539628
65                        Strap Material_Nylon     0.513634
72  Strap Material_Thermo Plastic Polyurethene     0.348913
63                      Strap Material_Leather     0.325556
10                                 Brand_apple     0.316458
68                       Strap Material_Rubber     0.301744
69                      Strap Material_Silicon     0.297849
62              Strap Material_Fluoroelastomer     0.284811
74                            Weight_50 - 75 g     0.283774

In [12]:
y_test

0     3.1
1     3.9
2     4.3
3     4.0
4     4.2
     ...
83    4.7
84    4.2
85    4.0
86    4.1
87    4.2
Name: Rating, Length: 88, dtype: float64

In [13]:
comparison_LR=pd.DataFrame({"Actual Ratings":y_test, "Predicted Ratings": y_pred})

In [14]:
comparison_LR.head(10)

   Actual Ratings  Predicted Ratings
0             3.1           3.656954
1             3.9           4.081767
2             4.3           4.462357
3             4.0           4.148384
4             4.2           3.839423
5             4.0           3.885687
6             4.1           4.400687
7             4.0           4.070227
8             4.1           4.109377
9             2.5           2.307367

In [15]:
joblib.dump(model, r"C:\Users\ASUS\OneDrive\Documents\ML Project\Smartwatches project\models\Linear_Regression.joblib")

print('Linear Regression Model Saved Successfully !!!')

Linear Regression Model Saved Successfully !!!

In [16]:
comparison_LR.to_csv(r"C:\Users\ASUS\OneDrive\Documents\ML Project\Smartwatches project\Dataset\Processed\Comparison_Linear_Regression.csv", index=False)

# DecisionTreeRegressor

In [17]:
DT_model=DecisionTreeRegressor(random_state=42)

In [18]:
DT_model.fit(X_train,y_train)

DecisionTreeRegressor(random_state=42)

In [19]:
feature_importance=pd.DataFrame({"Feature":X_train.columns,
                                 "Feature_Importance":DT_model.feature_importances_
                                }).sort_values(by='Feature_Importance', ascending=False)
feature_importance.head(10)

                    Feature  Feature_Importance
6   rating_placeholder_flag            0.414834
3         Number OF Ratings            0.156705
0             Current Price            0.142084
2       Discount Percentage            0.038821
75             Weight_75g +            0.034684
33        Strap Color_Black            0.033801
35        Strap Color_Brown            0.026676
27        Dial Shape_Curved            0.019363
1            Original Price            0.019221
5              Display Size            0.014847

In [20]:
y_pred_DT=DT_model.predict(X_test)
y_pred_DT

array([3.9, 3.7, 4.3, 4.1, 3.8, 4.1, 4.1, 4. , 4.1, 2.5, 4.3, 3.7, 4.4,
       4.1, 4.1, 2.5, 2.5, 3.7, 3.8, 4.2, 4.1, 4.3, 4.1, 3.9, 4.4, 4.6,
       3.7, 3.8, 3.9, 4.4, 3.9, 2.4, 4.2, 4.3, 3.8, 3.7, 4.1, 4.1, 4.4,
       4.7, 4.1, 4.6, 4.1, 4.3, 4.1, 4. , 3.9, 3.8, 3.8, 4.8, 3.6, 4.1,
       2.5, 4.6, 4.5, 3.7, 4.5, 3.9, 5. , 4.7, 4.1, 3.7, 4.3, 4. , 3.9,
       3.8, 3.8, 5. , 4.4, 4.5, 4.2, 4.2, 4.1, 3.7, 4.2, 4.6, 4.3, 4.2,
       4.3, 4.1, 4.7, 4.6, 3.9, 4.3, 4.2, 3.9, 4.1, 4.1])

### Comparison Dataframe

In [21]:
comparison_DT= pd.DataFrame({
    "Actual Rating": y_test,
    "Predicted Rating": y_pred_DT
})

comparison_DT.head()

   Actual Rating  Predicted Rating
0            3.1               3.9
1            3.9               3.7
2            4.3               4.3
3            4.0               4.1
4            4.2               3.8

In [22]:
comparison_DT.to_csv(
    r"C:\Users\ASUS\OneDrive\Documents\ML Project\Smartwatches project\Dataset\Processed\Comparison_Decision_Tree_Predictions.csv",
    index=False
)

In [23]:
joblib.dump(DT_model, r"C:\Users\ASUS\OneDrive\Documents\ML Project\Smartwatches project\models\Decision_Tree_Model.joblib")
print("Decision Tree Model Saved Successfully !!!")

Decision Tree Model Saved Successfully !!!

# Ridge

In [24]:
ridge_model=Ridge(alpha=1.0)

In [25]:
ridge_model.fit(X_train_scaled,y_train)

Ridge()

In [26]:
coef_Ridge = pd.DataFrame({
    "Feature": X_train.columns,
    "Coefficient": ridge_model.coef_}).sort_values(by='Coefficient', ascending=False)

coef_Ridge.head()

                     Feature  Coefficient
69    Strap Material_Silicon     0.128385
7   reviews_placeholder_flag     0.087626
17              Brand_garmin     0.078685
10               Brand_apple     0.069905
68     Strap Material_Rubber     0.069038

In [27]:
joblib.dump(ridge_model,r"C:\Users\ASUS\OneDrive\Documents\ML Project\Smartwatches project\models\Ridge_Model.joblib")
print("Ridge Model Saved Successfully !!!")

Ridge Model Saved Successfully !!!

### Comparing coefficient: Linear Regression vs Ridge

In [28]:
comparison_coef=pd.DataFrame({"Features":X_train.columns,
                              "Linear Coefficient":model.coef_,
                              "Ridge Coefficient": ridge_model.coef_})
comparison_coef["Difference"]=(comparison_coef['Linear Coefficient']-comparison_coef['Ridge Coefficient'])
comparison_coef.sort_values(by='Difference', ascending =False)
comparison_coef

,Features,Linear Coefficient,Ridge Coefficient,Difference
0,Current Price,1.988040e-06,0.030471,-0.030469
1,Original Price,2.041805e-06,0.031361,-0.031359
2,Discount Percentage,-4.291279e-05,-0.010162,0.010119
3,Number OF Ratings,7.186710e-07,0.028515,-0.028515
4,Battery Life (Days),2.658449e-04,0.002407,-0.002141
...,...,...,...,...
72,Strap Material_Thermo Plastic Polyurethene,3.489132e-01,0.043567,0.305346
73,Weight_35 - 50 g,1.064229e-01,0.032671,0.073752
74,Weight_50 - 75 g,2.837736e-01,0.046597,0.237177
75,Weight_75g +,-9.498204e-03,-0.003801,-0.005697
76,Weight_<= 20 g,3.228326e-02,0.010146,0.022137

In [29]:
comparison_coef.to_csv(r'C:\Users\ASUS\OneDrive\Documents\ML Project\Smartwatches project\Dataset\Processed\Ridge_vs_Linear.csv')

# Lasso

In [30]:
lasso_model=Lasso(alpha=1.0)

In [31]:
lasso_model.fit(X_train_scaled,y_train)

Lasso()

In [32]:
lasso_model.coef_

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [33]:
lasso_model.intercept_

np.float64(4.044540229885057)

In [34]:
y_pred_Lasso = lasso_model.predict(X_test_scaled)

In [35]:
coef_lasso=pd.DataFrame({"Feature":X_train.columns, "Coefficient":lasso_model.coef_}).sort_values(by="Coefficient", ascending=False)

### Comparing Actual Values and Predicted Values

In [36]:
comparison_lasso=pd.DataFrame({"Actual Values":y_test, "Predicted Values":y_pred_Lasso})

In [37]:
comparison_lasso.to_csv(r"C:\Users\ASUS\OneDrive\Documents\ML Project\Smartwatches project\Dataset\Processed\Comparison_Lasso.csv", index=False)

In [38]:
joblib.dump(lasso_model,r"C:\Users\ASUS\OneDrive\Documents\ML Project\Smartwatches project\models\Lasso_Model.joblib")
print("Lasso Model saved successfully !!!")

Lasso Model saved successfully !!!

# KNeighboursRegressor

In [39]:
# Keeping Neighbours=5 fro baseline
knn_model=KNeighborsRegressor(n_neighbors=5)

In [40]:
knn_model.fit(X_train_scaled, y_train)

KNeighborsRegressor()

In [41]:
y_pred_knn=knn_model.predict(X_test)

In [42]:
y_pred_knn

array([4.58, 4.58, 4.58, 4.58, 4.58, 4.58, 4.58, 4.14, 4.58, 4.58, 4.58,
       4.58, 4.58, 4.7 , 4.14, 4.58, 4.58, 4.7 , 4.58, 4.48, 4.14, 4.58,
       4.24, 4.58, 4.14, 4.7 , 4.58, 4.58, 4.58, 4.7 , 4.58, 4.58, 4.58,
       4.14, 4.58, 4.58, 4.7 , 4.58, 4.58, 4.7 , 4.58, 4.7 , 4.58, 4.14,
       4.14, 4.58, 4.48, 4.7 , 4.58, 4.7 , 4.58, 4.14, 4.58, 4.7 , 4.7 ,
       4.58, 4.58, 4.58, 4.7 , 4.7 , 4.14, 4.58, 4.58, 4.7 , 4.58, 4.7 ,
       4.58, 4.58, 4.48, 4.66, 4.58, 4.58, 4.58, 4.58, 4.58, 4.7 , 4.58,
       4.14, 4.58, 4.48, 4.7 , 4.7 , 4.58, 4.58, 4.14, 4.14, 4.48, 4.24])

In [43]:
joblib.dump(knn_model,r"C:\Users\ASUS\OneDrive\Documents\ML Project\Smartwatches project\models\KNN_Model.joblib")
print("KNN Model Saved Successfully !!!")

KNN Model Saved Successfully !!!

In [44]:
comparison_knn=pd.DataFrame({"Actual Values":y_test, "Predicted Values":y_pred_knn})

In [45]:
comparison_knn.to_csv(r"C:\Users\ASUS\OneDrive\Documents\ML Project\Smartwatches project\Dataset\Processed\Comparison_KNN.csv")

# RandomForestRegressor

In [46]:
# 100 trees(Baseline)

rfr_model=RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

In [47]:
rfr_model.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [48]:
y_pred_rfr=rfr_model.predict(X_test)

In [49]:
y_pred_rfr.shape

(88,)

### Feature Importance

In [50]:
feature_importance_rfr=pd.DataFrame({"Features":X_train.columns, "Feature Importance":rfr_model.feature_importances_}).sort_values(by="Feature Importance", ascending=False)

In [51]:
feature_importance_rfr.head(10)

                   Features  Feature Importance
6   rating_placeholder_flag            0.404938
3         Number OF Ratings            0.179184
0             Current Price            0.156320
2       Discount Percentage            0.034218
5              Display Size            0.030987
35        Strap Color_Brown            0.018050
1            Original Price            0.017976
27        Dial Shape_Curved            0.017040
4       Battery Life (Days)            0.013556
25          Brand_zebronics            0.013492

In [52]:
comparison_rfr=pd.DataFrame({"Actual Values":y_test, "Predicted Values" : y_pred_rfr})
comparison_rfr

    Actual Values  Predicted Values
0             3.1             3.440
1             3.9             3.763
2             4.3             4.277
3             4.0             4.047
4             4.2             4.085
..            ...               ...
83            4.7             4.375
84            4.2             4.186
85            4.0             4.004
86            4.1             4.093
87            4.2             4.106

[88 rows x 2 columns]

In [53]:
comparison_rfr.to_csv(r"C:\Users\ASUS\OneDrive\Documents\ML Project\Smartwatches project\Dataset\Processed\Comparison_rfr.csv")

In [54]:
joblib.dump(rfr_model, r"C:\Users\ASUS\OneDrive\Documents\ML Project\Smartwatches project\models\RFR_model.joblib")
print("Model Saved Successfully !!!")

Model Saved Successfully !!!

# GradientBoostingRegressor

In [55]:
gbr_model=GradientBoostingRegressor(
    n_estimators=100,
    learning_rate=0.1,
    random_state=42
)

In [56]:
gbr_model.fit(X_train, y_train)

GradientBoostingRegressor(random_state=42)

In [57]:
y_pred_gbr=gbr_model.predict(X_test)
y_pred_gbr.shape

(88,)

In [58]:
feature_importance_gbr=pd.DataFrame({"Features":X_train.columns, "Feature Importance":gbr_model.feature_importances_}).sort_values(by="Feature Importance", ascending=False)
feature_importance_gbr.head(10)

                   Features  Feature Importance
6   rating_placeholder_flag            0.459022
3         Number OF Ratings            0.180403
0             Current Price            0.146337
25          Brand_zebronics            0.033172
2       Discount Percentage            0.026523
35        Strap Color_Brown            0.019100
27        Dial Shape_Curved            0.018726
75             Weight_75g +            0.015936
14         Brand_fire-boltt            0.012897
16             Brand_fossil            0.010306

In [59]:
comparison_gbr=pd.DataFrame({"Actual values": y_test, "Predicted Values":y_pred_gbr})
comparison_gbr

    Actual values  Predicted Values
0             3.1          3.404467
1             3.9          3.830968
2             4.3          4.409437
3             4.0          4.003486
4             4.2          4.010178
..            ...               ...
83            4.7          4.215954
84            4.2          4.161596
85            4.0          4.051226
86            4.1          4.086133
87            4.2          4.137672

[88 rows x 2 columns]

In [60]:
comparison_gbr.to_csv(r"C:\Users\ASUS\OneDrive\Documents\ML Project\Smartwatches project\Dataset\Processed\Comparison_gbr.csv", index=False)

In [61]:
joblib.dump(gbr_model, r"C:\Users\ASUS\OneDrive\Documents\ML Project\Smartwatches project\models\GBR_model.joblib")
print("Model Saved Successfully !!")

Model Saved Successfully !!

# XGBoost

In [106]:
xgb_model=XGBRegressor(
    n_estimators=100,
    learning_rate=0.1,
    random_state=42
)

In [107]:
# Removing any [, ], <, >, =

for col in X_train.columns:
    if "[" in col or "]"in col or "<" in col or  "=" in col:
        print(col)
        X_train.columns=(X_train.columns
            .str.replace("[", "", regex=False)
            .str.replace("]", "", regex=False)
            .str.replace("<", "less than",  regex=False)
            .str.replace(">", "greater than", regex=False)
            .str.replace("=", "equal to", regex=False)
        )
        X_test.columns=(X_test.columns
            .str.replace("[", "", regex=False)
            .str.replace("]", "", regex=False)
            .str.replace("<", "less than", regex=False)
            .str.replace(">", "greater than", regex=False)
            .str.replace("=", "equal to", regex=False)
        )

In [108]:
xgb_model.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.1, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=100,
             n_jobs=None, num_parallel_tree=None, ...)

In [109]:
y_pred_xgb=xgb_model.predict(X_test)

### Feature Importance

In [110]:
feature_importance_xgb=pd.DataFrame({"Features":X_train.columns, "Feature Importance":xgb_model.feature_importances_}).sort_values(by="Feature Importance", ascending=False)
feature_importance.head(10)

                    Feature  Feature_Importance
6   rating_placeholder_flag            0.414834
3         Number OF Ratings            0.156705
0             Current Price            0.142084
2       Discount Percentage            0.038821
75             Weight_75g +            0.034684
33        Strap Color_Black            0.033801
35        Strap Color_Brown            0.026676
27        Dial Shape_Curved            0.019363
1            Original Price            0.019221
5              Display Size            0.014847

In [111]:
comparison_xgb=pd.DataFrame({"Actual":y_test, "Predicted":y_pred_xgb})
comparison_xgb.to_csv(r"C:\Users\ASUS\OneDrive\Documents\ML Project\Smartwatches project\Dataset\Processed\Comparison_xgb.csv")

In [112]:
joblib.dump(xgb_model, r"C:\Users\ASUS\OneDrive\Documents\ML Project\Smartwatches project\models\XGB_model.joblib")
print("Model Saved successfully !!!")

Model Saved successfully !!!