# Pre-Processing and Feature Engineering

In [22]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler

In [23]:
df=pd.read_csv(r"C:\Users\ASUS\OneDrive\Documents\ML Project\Smartwatches project\Dataset\cleaned_dataset.csv")
df.head()

,Brand,Current Price,Original Price,Discount Percentage,Rating,Number OF Ratings,Model Name,Dial Shape,Strap Color,Strap Material,Touchscreen,Battery Life (Days),Bluetooth,Display Size,Weight,rating_placeholder_flag,reviews_placeholder_flag,price_logic_flag
0,noise,82990.0,89900.0,7.686318,4.0,65.0,Wrb-sw-colorfitpro4alpha-std-rgld_pnk,Missing,Missing,Missing,1,8.0,1,1.5,35 - 50 g,False,False,False
1,fire-boltt,3799.0,16999.0,77.651627,4.3,20788.0,BSW046,Missing,Missing,Silicon,1,3.5,1,1.8,50 - 75 g,False,False,False
2,boat,1999.0,7990.0,74.981227,3.8,21724.0,Wave Call,Missing,Missing,Silicon,1,8.0,1,1.7,35 - 50 g,False,False,False
3,fire-boltt,1799.0,19999.0,91.004550,4.3,13244.0,BSW053,Missing,Missing,Silicon,1,3.5,1,1.8,75g +,False,False,False
4,noise,1599.0,4999.0,68.013603,4.1,13901.0,Wrb-sw-colorfitpulsegobuzz-std-blk_blk,Missing,Missing,Other,1,8.0,1,1.7,35 - 50 g,False,False,False

In [24]:
df.shape

(436, 18)

In [25]:
X=df.drop(columns=['Rating', 'Model Name'])
y=df['Rating']
X.columns

Index(['Brand', 'Current Price', 'Original Price', 'Discount Percentage',
       'Number OF Ratings', 'Dial Shape', 'Strap Color', 'Strap Material',
       'Touchscreen', 'Battery Life (Days)', 'Bluetooth', 'Display Size',
       'Weight', 'rating_placeholder_flag', 'reviews_placeholder_flag',
       'price_logic_flag'],
      dtype='object')

In [26]:
Categorical_columns=X.select_dtypes(include=["object"]).columns

numerical_columns=X.select_dtypes(exclude=["object","bool"]).columns

binary_columns=df.select_dtypes(include='bool').columns

print(type(numerical_columns))

for col in numerical_columns:
    if col in ['Touchscreen', 'Bluetooth']:
        numerical_columns=numerical_columns.drop(col)
        

print("No. of categorical columns: ",len(Categorical_columns))
print("No. of numerical columns: ", len(numerical_columns))
print("No. of numerical columns: ", len(binary_columns))

print(numerical_columns)

<class 'pandas.core.indexes.base.Index'>
No. of categorical columns:  5
No. of numerical columns:  6
No. of numerical columns:  3
Index(['Current Price', 'Original Price', 'Discount Percentage',
       'Number OF Ratings', 'Battery Life (Days)', 'Display Size'],
      dtype='object')

In [27]:
X_train, X_test, y_train, y_test= train_test_split(X, y, random_state=42, test_size=0.2)

In [28]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(348, 16)
(88, 16)
(348,)
(88,)

In [29]:
X_train

,Brand,Current Price,Original Price,Discount Percentage,Number OF Ratings,Dial Shape,Strap Color,Strap Material,Touchscreen,Battery Life (Days),Bluetooth,Display Size,Weight,rating_placeholder_flag,reviews_placeholder_flag,price_logic_flag
265,garmin,67490.0,67990.0,0.735402,6022.0,Circle,Grey,Silicon,1,12.500000,1,0.1,20 - 35 g,False,False,False
405,fire-boltt,3299.0,9999.0,67.006701,5.0,Square,Grey,Silicon,1,22.000000,1,1.7,20 - 35 g,True,False,False
31,boat,1449.0,5990.0,75.809683,3944.0,Missing,Missing,Missing,1,14.077392,1,1.7,35 - 50 g,False,False,False
84,pebble,4499.0,7499.0,40.005334,94.0,Missing,Missing,Missing,1,12.500000,1,1.3,35 - 50 g,False,False,False
299,fossil,16495.0,7999.0,-106.213277,996.0,Circle,Silver,Stainless Steel,0,8.000000,1,1.1,20 - 35 g,False,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,gizmore,1499.0,5999.0,75.012502,996.0,Missing,Missing,Missing,1,14.077392,1,1.5,75g +,False,True,False
106,fire-boltt,1399.0,11999.0,88.340695,1519.0,Missing,Missing,Silicon,1,8.000000,1,1.8,75g +,False,False,False
270,huawei,14990.0,20990.0,28.585041,3228.0,Circle,Black,Fluoroelastomer,1,8.000000,1,1.8,20 - 35 g,False,False,False
348,pebble,2799.0,7499.0,62.675023,12644.0,Rectangle,Black,Silicon,1,22.000000,1,1.9,75g +,False,False,False
102,fire-boltt,2499.0,9999.0,75.007501,23302.0,Missing,Missing,Silicon,1,3.500000,1,1.8,50 - 75 g,False,False,False

# Encoding categorical values

In [30]:
encoder=OneHotEncoder(drop='first', handle_unknown='ignore', sparse_output=False)

X_train_encoded=encoder.fit_transform(X_train[Categorical_columns])
X_test_encoded=encoder.transform(X_test[Categorical_columns])

c:\Users\ASUS\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [2, 3] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)

In [31]:
X_train_encoded.shape

(348, 68)

In [32]:
X_train_encoded

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 1., 0., 0.]], shape=(348, 68))

In [33]:
cat_col_names=encoder.get_feature_names_out(Categorical_columns)

In [34]:
X_train_encoded=pd.DataFrame(X_train_encoded, columns=cat_col_names, index=X_train.index)

X_test_encoded=pd.DataFrame(X_test_encoded, columns=cat_col_names, index=X_test.index)

X_train=pd.concat( [X_train[numerical_columns], X_train[binary_columns], X_train_encoded], axis=1)
X_test=pd.concat([X_test[numerical_columns], X_test[binary_columns], X_test_encoded], axis=1)

In [44]:
X_train

,Current Price,Original Price,Discount Percentage,Number OF Ratings,Battery Life (Days),Display Size,rating_placeholder_flag,reviews_placeholder_flag,price_logic_flag,Brand_ambrane,...,Strap Material_Plastic,Strap Material_Rubber,Strap Material_Silicon,Strap Material_Stainless Steel,Strap Material_Synthetic,Strap Material_Thermo Plastic Polyurethene,Weight_35 - 50 g,Weight_50 - 75 g,Weight_75g +,Weight_<= 20 g
265,67490.0,67990.0,0.735402,6022.0,12.500000,0.1,False,False,False,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
405,3299.0,9999.0,67.006701,5.0,22.000000,1.7,True,False,False,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31,1449.0,5990.0,75.809683,3944.0,14.077392,1.7,False,False,False,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
84,4499.0,7499.0,40.005334,94.0,12.500000,1.3,False,False,False,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
299,16495.0,7999.0,-106.213277,996.0,8.000000,1.1,False,True,True,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,1499.0,5999.0,75.012502,996.0,14.077392,1.5,False,True,False,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
106,1399.0,11999.0,88.340695,1519.0,8.000000,1.8,False,False,False,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
270,14990.0,20990.0,28.585041,3228.0,8.000000,1.8,False,False,False,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
348,2799.0,7499.0,62.675023,12644.0,22.000000,1.9,False,False,False,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
102,2499.0,9999.0,75.007501,23302.0,3.500000,1.8,False,False,False,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

# Scaling Numerical Values

In [36]:
scaler=StandardScaler()

In [42]:
X_train_scaled=pd.DataFrame(scaler.fit_transform(X_train), columns=X_train.columns)
X_test_scaled=pd.DataFrame(scaler.transform(X_test), columns=X_test.columns)

In [38]:
X_train

,Current Price,Original Price,Discount Percentage,Number OF Ratings,Battery Life (Days),Display Size,rating_placeholder_flag,reviews_placeholder_flag,price_logic_flag,Brand_ambrane,...,Strap Material_Plastic,Strap Material_Rubber,Strap Material_Silicon,Strap Material_Stainless Steel,Strap Material_Synthetic,Strap Material_Thermo Plastic Polyurethene,Weight_35 - 50 g,Weight_50 - 75 g,Weight_75g +,Weight_<= 20 g
265,67490.0,67990.0,0.735402,6022.0,12.500000,0.1,False,False,False,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
405,3299.0,9999.0,67.006701,5.0,22.000000,1.7,True,False,False,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31,1449.0,5990.0,75.809683,3944.0,14.077392,1.7,False,False,False,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
84,4499.0,7499.0,40.005334,94.0,12.500000,1.3,False,False,False,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
299,16495.0,7999.0,-106.213277,996.0,8.000000,1.1,False,True,True,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,1499.0,5999.0,75.012502,996.0,14.077392,1.5,False,True,False,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
106,1399.0,11999.0,88.340695,1519.0,8.000000,1.8,False,False,False,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
270,14990.0,20990.0,28.585041,3228.0,8.000000,1.8,False,False,False,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
348,2799.0,7499.0,62.675023,12644.0,22.000000,1.9,False,False,False,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
102,2499.0,9999.0,75.007501,23302.0,3.500000,1.8,False,False,False,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [39]:
X_train[numerical_columns].describe()

,Current Price,Original Price,Discount Percentage,Number OF Ratings,Battery Life (Days),Display Size
count,348.000000,348.000000,348.000000,348.000000,348.000000,348.000000
mean,13111.143678,13623.126437,-7.147918,9597.764368,14.214427,1.409195
std,17397.940338,13783.189873,170.652400,39973.218761,7.637914,0.484071
min,1199.000000,1669.000000,-1650.093762,1.000000,0.750000,0.100000
25%,2499.000000,5999.000000,11.892016,92.750000,8.000000,1.300000
50%,3999.000000,7999.000000,44.450618,996.000000,17.500000,1.500000
75%,18431.250000,14996.000000,62.555478,4353.750000,22.000000,1.700000
max,139990.000000,96390.000000,91.004550,619130.000000,22.000000,3.000000

In [40]:
X_train.to_csv(r'C:\Users\ASUS\OneDrive\Documents\ML Project\Smartwatches project\Dataset\Processed\X_train.csv', index=False)
X_test.to_csv(r'C:\Users\ASUS\OneDrive\Documents\ML Project\Smartwatches project\Dataset\Processed\X_test.csv', index=False)
y_train.to_csv(r'C:\Users\ASUS\OneDrive\Documents\ML Project\Smartwatches project\Dataset\Processed\y_train.csv', index=False)
y_test.to_csv(r'C:\Users\ASUS\OneDrive\Documents\ML Project\Smartwatches project\Dataset\Processed\y_test.csv', index=False)

In [43]:
X_train_scaled.to_csv(r'C:\Users\ASUS\OneDrive\Documents\ML Project\Smartwatches project\Dataset\Processed\X_train_scaled.csv', index=False)
X_test_scaled.to_csv(r'C:\Users\ASUS\OneDrive\Documents\ML Project\Smartwatches project\Dataset\Processed\X_test_scaled.csv', index=False)