# Pre-Processing and Feature Engineering

In [302]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler

In [303]:
df=pd.read_csv(r"C:\Users\ASUS\OneDrive\Documents\ML Project\Smartwatches project\Dataset\cleaned_dataset.csv")
df.head()

,Brand,Current Price,Original Price,Discount Percentage,Rating,Number OF Ratings,Model Name,Dial Shape,Strap Color,Strap Material,Touchscreen,Battery Life (Days),Bluetooth,Display Size,Weight,rating_placeholder_flag,reviews_placeholder_flag,price_logic_flag
0,noise,82990.0,89900.0,7.686318,4.0,65.0,Wrb-sw-colorfitpro4alpha-std-rgld_pnk,Missing,Missing,Missing,1,8.0,1,1.5,35 - 50 g,False,False,False
1,fire-boltt,3799.0,16999.0,77.651627,4.3,20788.0,BSW046,Missing,Missing,Silicon,1,3.5,1,1.8,50 - 75 g,False,False,False
2,boat,1999.0,7990.0,74.981227,3.8,21724.0,Wave Call,Missing,Missing,Silicon,1,8.0,1,1.7,35 - 50 g,False,False,False
3,fire-boltt,1799.0,19999.0,91.004550,4.3,13244.0,BSW053,Missing,Missing,Silicon,1,3.5,1,1.8,75g +,False,False,False
4,noise,1599.0,4999.0,68.013603,4.1,13901.0,Wrb-sw-colorfitpulsegobuzz-std-blk_blk,Missing,Missing,Other,1,8.0,1,1.7,35 - 50 g,False,False,False

In [304]:
df.shape

(436, 18)

In [305]:
X=df.drop(columns=['Rating', 'Model Name'])
y=df['Rating']
X.columns

Index(['Brand', 'Current Price', 'Original Price', 'Discount Percentage',
       'Number OF Ratings', 'Dial Shape', 'Strap Color', 'Strap Material',
       'Touchscreen', 'Battery Life (Days)', 'Bluetooth', 'Display Size',
       'Weight', 'rating_placeholder_flag', 'reviews_placeholder_flag',
       'price_logic_flag'],
      dtype='object')

In [306]:
Categorical_columns=X.select_dtypes(include=["object"]).columns

numerical_columns=X.select_dtypes(exclude=["object","bool"]).columns

binary_columns=df.select_dtypes(include='bool').columns

print(type(numerical_columns))

for col in numerical_columns:
    if col in ['Touchscreen', 'Bluetooth']:
        numerical_columns=numerical_columns.drop(col)
        

print("No. of categorical columns: ",len(Categorical_columns))
print("No. of numerical columns: ", len(numerical_columns))
print("No. of numerical columns: ", len(binary_columns))

print(numerical_columns)

<class 'pandas.core.indexes.base.Index'>
No. of categorical columns:  5
No. of numerical columns:  6
No. of numerical columns:  3
Index(['Current Price', 'Original Price', 'Discount Percentage',
       'Number OF Ratings', 'Battery Life (Days)', 'Display Size'],
      dtype='object')

In [307]:
X_train, X_test, y_train, y_test= train_test_split(X, y, random_state=42, test_size=0.2)

In [308]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(348, 16)
(88, 16)
(348,)
(88,)

# Encoding categorical values

In [309]:
encoder=OneHotEncoder(drop='first', handle_unknown='ignore', sparse_output=False)

X_train_encoded=encoder.fit_transform(X_train[Categorical_columns])
X_test_encoded=encoder.transform(X_test[Categorical_columns])

c:\Users\ASUS\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [2, 3] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)

In [310]:
X_train_encoded.shape

(348, 68)

In [311]:
X_train_encoded

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 1., 0., 0.]], shape=(348, 68))

In [312]:
cat_col_names=encoder.get_feature_names_out(Categorical_columns)

In [313]:
X_train_encoded=pd.DataFrame(X_train_encoded, columns=cat_col_names, index=X_train.index)

X_test_encoded=pd.DataFrame(X_test_encoded, columns=cat_col_names, index=X_test.index)

X_train=pd.concat( [X_train[numerical_columns], X_train[binary_columns], X_train_encoded], axis=1)
X_test=pd.concat([X_test[numerical_columns], X_test[binary_columns], X_test_encoded], axis=1)

In [314]:
X_train

,Current Price,Original Price,Discount Percentage,Number OF Ratings,Battery Life (Days),Display Size,rating_placeholder_flag,reviews_placeholder_flag,price_logic_flag,Brand_ambrane,...,Strap Material_Plastic,Strap Material_Rubber,Strap Material_Silicon,Strap Material_Stainless Steel,Strap Material_Synthetic,Strap Material_Thermo Plastic Polyurethene,Weight_35 - 50 g,Weight_50 - 75 g,Weight_75g +,Weight_<= 20 g
265,67490.0,67990.0,0.735402,6022.0,12.500000,0.1,False,False,False,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
405,3299.0,9999.0,67.006701,5.0,22.000000,1.7,True,False,False,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31,1449.0,5990.0,75.809683,3944.0,14.077392,1.7,False,False,False,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
84,4499.0,7499.0,40.005334,94.0,12.500000,1.3,False,False,False,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
299,16495.0,7999.0,-106.213277,996.0,8.000000,1.1,False,True,True,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,1499.0,5999.0,75.012502,996.0,14.077392,1.5,False,True,False,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
106,1399.0,11999.0,88.340695,1519.0,8.000000,1.8,False,False,False,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
270,14990.0,20990.0,28.585041,3228.0,8.000000,1.8,False,False,False,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
348,2799.0,7499.0,62.675023,12644.0,22.000000,1.9,False,False,False,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
102,2499.0,9999.0,75.007501,23302.0,3.500000,1.8,False,False,False,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [315]:
print(X_train.head())

print(X_train.shape)

print(X_test.shape)

     Current Price  Original Price  Discount Percentage  Number OF Ratings  \
265        67490.0         67990.0             0.735402             6022.0
405         3299.0          9999.0            67.006701                5.0
31          1449.0          5990.0            75.809683             3944.0
84          4499.0          7499.0            40.005334               94.0
299        16495.0          7999.0          -106.213277              996.0

     Battery Life (Days)  Display Size  rating_placeholder_flag  \
265            12.500000           0.1                    False
405            22.000000           1.7                     True
31             14.077392           1.7                    False
84             12.500000           1.3                    False
299             8.000000           1.1                    False

     reviews_placeholder_flag  price_logic_flag  Brand_ambrane  ...  \
265                     False             False            0.0  ...
405                     False             False            0.0  ...
31                      False             False            0.0  ...
84                      False             False            0.0  ...
299                      True              True            0.0  ...

     Strap Material_Plastic  Strap Material_Rubber  Strap Material_Silicon  \
265                     0.0                    0.0                     1.0
405                     0.0                    0.0                     1.0
31                      0.0                    0.0                     0.0
84                      0.0                    0.0                     0.0
299                     0.0                    0.0                     0.0

     Strap Material_Stainless Steel  Strap Material_Synthetic  \
265                             0.0                       0.0
405                             0.0                       0.0
31                              0.0                       0.0
84                              0.0                       0.0
299                             1.0                       0.0

     Strap Material_Thermo Plastic Polyurethene  Weight_35 - 50 g  \
265                                         0.0               0.0
405                                         0.0               0.0
31                                          0.0               1.0
84                                          0.0               1.0
299                                         0.0               0.0

     Weight_50 - 75 g  Weight_75g +  Weight_<= 20 g
265               0.0           0.0             0.0
405               0.0           0.0             0.0
31                0.0           0.0             0.0
84                0.0           0.0             0.0
299               0.0           0.0             0.0

[5 rows x 77 columns]
(348, 77)
(88, 77)

# Scaling Numerical Values

In [316]:
scaler=StandardScaler()

In [317]:
X_train[numerical_columns]=scaler.fit_transform(X_train[numerical_columns])
X_test[numerical_columns]=scaler.transform(X_test[numerical_columns])

In [318]:
X_train

,Current Price,Original Price,Discount Percentage,Number OF Ratings,Battery Life (Days),Display Size,rating_placeholder_flag,reviews_placeholder_flag,price_logic_flag,Brand_ambrane,...,Strap Material_Plastic,Strap Material_Rubber,Strap Material_Silicon,Strap Material_Stainless Steel,Strap Material_Synthetic,Strap Material_Thermo Plastic Polyurethene,Weight_35 - 50 g,Weight_50 - 75 g,Weight_75g +,Weight_<= 20 g
265,3.130092,3.950113,0.046262,-0.089583,-0.224786,-2.708448,False,False,False,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
405,-0.564795,-0.263317,0.435162,-0.240325,1.020800,0.601613,True,False,False,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31,-0.671283,-0.554597,0.486820,-0.141642,-0.017967,0.601613,False,False,False,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
84,-0.495722,-0.444958,0.276710,-0.238096,-0.224786,-0.225902,False,False,False,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
299,0.194778,-0.408630,-0.581345,-0.215498,-0.814800,-0.639660,False,True,True,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,-0.668405,-0.553943,0.482142,-0.215498,-0.017967,0.187856,False,True,False,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
106,-0.674161,-0.118004,0.560356,-0.202395,-0.814800,0.808492,False,False,False,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
270,0.108149,0.535252,0.209692,-0.159580,-0.814800,0.808492,False,False,False,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
348,-0.593576,-0.444958,0.409742,0.076317,1.020800,1.015371,False,False,False,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
102,-0.610844,-0.263317,0.482113,0.343329,-1.404815,0.808492,False,False,False,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [319]:
X_train[numerical_columns].describe()

,Current Price,Original Price,Discount Percentage,Number OF Ratings,Battery Life (Days),Display Size
count,3.480000e+02,3.480000e+02,3.480000e+02,3.480000e+02,3.480000e+02,3.480000e+02
mean,8.932829e-18,-2.552237e-17,-1.020895e-17,2.935072e-17,-1.225074e-16,-6.125368e-16
std,1.001440e+00,1.001440e+00,1.001440e+00,1.001440e+00,1.001440e+00,1.001440e+00
min,-6.856729e-01,-8.685463e-01,-9.641303e+00,-2.404255e-01,-1.765379e+00,-2.708448e+00
25%,-6.108438e-01,-5.539432e-01,1.117321e-01,-2.381269e-01,-8.148003e-01,-2.259022e-01
50%,-5.245026e-01,-4.086300e-01,3.027958e-01,-2.154980e-01,4.307857e-01,1.878555e-01
75%,3.062297e-01,9.974834e-02,4.090406e-01,-1.313771e-01,1.020800e+00,6.016132e-01
max,7.303252e+00,6.013561e+00,5.759884e-01,1.527047e+01,1.020800e+00,3.291038e+00

In [320]:
X_train.to_csv(r'C:\Users\ASUS\OneDrive\Documents\ML Project\Smartwatches project\Dataset\Processed\X_train.csv')
X_test.to_csv(r'C:\Users\ASUS\OneDrive\Documents\ML Project\Smartwatches project\Dataset\Processed\X_test.csv')
y_train.to_csv(r'C:\Users\ASUS\OneDrive\Documents\ML Project\Smartwatches project\Dataset\Processed\y_train.csv')
y_test.to_csv(r'C:\Users\ASUS\OneDrive\Documents\ML Project\Smartwatches project\Dataset\Processed\y_test.csv')